### PR TITLE
fix(scm_integration): fix terraform import

### LINKED ISSUE #82: [SCM Integration] Fix terraform import
Currently `terrafrom import` is not working with `scm_integration`

### PR DESCRIPTION
**Pull request by curzolapierre**
Fix #82

### CODE REVIEW

File: scalingo/resource_scalingo_scm_integration.go [hunk 1]
```diff
@@ -115,9 +115,7 @@ func resourceScmIntegrationDelete(ctx context.Context, d *schema.ResourceData, m
 }
 
 func resourceScmIntegrationImport(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
-	d.SetId(d.Id())
-
-	diags := resourceGithubLinkRead(ctx, d, meta)
```
Comment (EtienneM) [inline scalingo/resource_scalingo_scm_integration.go:120]: I must say that I have no idea what this change does, but I am happy to validate it ^^

Joke aside, if you are sure about what it does and that it works, LGTM

**Review by EtienneM — APPROVED** [review]
