### PR TITLE
Fix update and read on alerts resources

### LINKED ISSUE #91: resources Alerts read doesn't provide notifiers
The API isn't returning the `notifiers` field on GET /alerts/:id

### LINKED ISSUE #92: resources Alerts update doesn't provide notifiers
The API isn't returning the `notifiers` field on PATCH /alerts/:id

### PR DESCRIPTION
**Pull request by SCedricThomas**
fix #91 
fix #92

### CODE REVIEW

File: scalingo/resource_scalingo_alert.go [hunk 1]
```diff
@@ -210,7 +218,7 @@ func resourceAlertsUpdate(ctx context.Context, d *schema.ResourceData, meta inte
 			"send_when_below":         alertUpdate.SendWhenBelow,
 			"duration_before_trigger": alertUpdate.DurationBeforeTrigger.String(),
 			"remind_every":            alertUpdate.RemindEvery,
-			"notifiers":               alertUpdate.Notifiers,
+			"notifiers":               alertUpdateParams.Notifiers,
```
Comment (curzolapierre) [inline scalingo/resource_scalingo_alert.go:221]: Why are you using `alertUpdateParams` here?
Is the `client.AlertUpdate` not returns the correct notifier?

**Review by curzolapierre — COMMENTED** [review]
Just a question, otherwise LGTM

File: scalingo/resource_scalingo_alert.go (hunk 1 above)
Comment (SCedricThomas) [reply scalingo/resource_scalingo_alert.go:221]: The GET by id and the PATCH routes aren't returning the notifiers, so I have to save them from the input parameters

**Review by curzolapierre — APPROVED** [review]
